// Package Data
export const DATA_LOAD_REQUEST = 'DATA_PARSE_REQUEST';
export const DATA_LOAD_SUCCESS = 'DATA_PARSE_SUCCESS';
export const DATA_LOAD_FAILURE = 'DATA_PARSE_FAILURE';

export const PACKAGE_LIST_REQUEST = 'PACKAGE_LIST_REQUEST';
export const PACKAGE_LIST_SUCCESS = 'PACKAGE_LIST_SUCCESS';
export const PACKAGE_LIST_FAILURE = 'PACKAGE_LIST_FAILURE';

export const PACKAGE_DETAIL_REQUEST = 'PACKAGE_DETAIL_REQUEST';
export const PACKAGE_DETAIL_SUCCESS = 'PACKAGE_DETAIL_SUCCESS';
export const PACKAGE_DETAIL_FAILURE = 'PACKAGE_DETAIL_FAILURE';

export const PACKAGE_DEPENDENCIES_REQUEST = 'PACKAGE_DEPENDENCIES_REQUEST';
export const PACKAGE_DEPENDENCIES_SUCCESS = 'PACKAGE_DEPENDENCIES_SUCCESS';
export const PACKAGE_DEPENDENCIES_FAILURE = 'PACKAGE_DEPENDENCIES_FAILURE';

export const PACKAGE_PARENTS_REQUEST = 'PACKAGE_PARENTS_REQUEST';
export const PACKAGE_PARENTS_SUCCESS = 'PACKAGE_PARENTS_SUCCESS';
export const PACKAGE_PARENTS_FAILURE = 'PACKAGE_PARENTS_FAILURE';
